### GET request with a header
GET https://api.openweathermap.org/data/2.5/forecast?id=6454159&units=metric&appid=$(OPENWEATHER_APIKEY)
Accept: application/json

### GET request with a header
GET https://pro.openweathermap.org/data/2.5/forecast/hourly?lat=37.785834&lon=-122.406417&units=metric&appid=a426b9f2f27a821c5ebd69e882daff65
Accept: application/json

### GET request with a header
GET https://pixabay.com/api/?q=Paris&key=$(PIXABAY_APIKEY)&image_type=photo
Accept: application/json

### GET request with a header
GET http://api.openweathermap.org/geo/1.0/reverse?lat=47.902889&lon=1.90389&limit=1&appid=a426b9f2f27a821c5ebd69e882daff65
Accept: application/json